#coding=utf-8
#import libs 
import sys
import os
from   os.path import abspath, dirname
sys.path.insert(0,abspath(dirname(__file__)))
import login_main_cmd
import login_main_sty
import Fun
import EXUIControl
EXUIControl.FunLib = Fun
EXUIControl.G_ExeDir = Fun.G_ExeDir
EXUIControl.G_ResDir = Fun.G_ResDir
import tkinter
from   tkinter import *
import tkinter.ttk
import tkinter.font
from   PIL import Image,ImageTk
#Add your Varial Here: (Keep This Line of comments)
#Define UI Class
class  login_main:
    def __init__(self,root,isTKroot = True,params=None):
        uiName = Fun.GetUIName(root,self.__class__.__name__)
        self.uiName = uiName
        Fun.Register(uiName,'UIClass',self)
        self.root = root
        self.isTKroot = isTKroot
        self.firstRun = True
        Fun.G_UIParamsDictionary[uiName]=params
        Fun.G_UICommandDictionary[uiName]=login_main_cmd
        Fun.Register(uiName,'root',root)
        style = login_main_sty.SetupStyle(isTKroot)
        if isTKroot == True:
            Fun.SetTitleBar(root,titleText='Form1',isDarkMode=False)
            Fun.CenterDlg(uiName,root,1440,900)
            Fun.WindowDraggable(root,False,0,'#ffffff')
            root.wm_attributes("-topmost",1)
            root['background'] = '#FFFFFF'
        Form_1= tkinter.Canvas(root,width = 10,height = 4)
        Form_1.pack(side=tkinter.TOP,fill=tkinter.BOTH,expand=True)#pack
        Form_1.configure(width = 1440)
        Form_1.configure(height = 900)
        Form_1.configure(bg = "#FFFFFF")
        Form_1.configure(highlightthickness = 0)
        Fun.Register(uiName,'Form_1',Form_1)
        Fun.SetUIRootSize(uiName,1440,900)
        #Create the elements of root 
        LabelButton_2= EXUIControl.LabelButton(Form_1)
        Fun.Register(uiName,'PyMe_LabelButton_2',LabelButton_2,'login')
        LabelButton_2.SetText("登录")
        LabelButton_2.SetBGColor("#FFFFFF")
        LabelButton_2.SetFGColor("#2468F2")
        LabelButton_2_TitleFont=tkinter.font.Font(family='微软雅黑', size=26,weight='normal',slant='roman',underline=0,overstrike=0)
        LabelButton_2.SetFont(LabelButton_2_TitleFont)
        LabelButton_2.SetBGColor_Hover("#FFFFFF")
        LabelButton_2.SetFGColor_Hover("#2468F2")
        LabelButton_2.SetBGColor_Click("#FFFFFF")
        LabelButton_2.SetFGColor_Click("#2468F2")
        Fun.SetControlPlace(uiName,'PyMe_LabelButton_2',0.5694444444444444,0.2233,0.1354,0.05333,'nw',True,True)
        LabelButton_2.Redraw()
        LabelButton_2.SetCommandFunction(login_main_cmd.login_onCommand,self.uiName,"login")
        LabelButton_3= EXUIControl.LabelButton(Form_1)
        Fun.Register(uiName,'PyMe_LabelButton_3',LabelButton_3,'reg')
        LabelButton_3.SetText("注册")
        LabelButton_3.SetBGColor("#FFFFFF")
        LabelButton_3.SetFGColor("#000000")
        LabelButton_3_TitleFont=tkinter.font.Font(family='微软雅黑', size=26,weight='normal',slant='roman',underline=0,overstrike=0)
        LabelButton_3.SetFont(LabelButton_3_TitleFont)
        LabelButton_3.SetBGColor_Hover("#AAAAAA")
        LabelButton_3.SetFGColor_Hover("#000000")
        LabelButton_3.SetBGColor_Click("#AAAAAA")
        LabelButton_3.SetFGColor_Click("#FF0000")
        Fun.SetControlPlace(uiName,'PyMe_LabelButton_3',0.7048611111111112,0.22333333333333333,0.13541666666666666,0.05333333333333334,'nw',True,True)
        LabelButton_3.Redraw()
        LabelButton_3.SetCommandFunction(login_main_cmd.reg_onCommand,self.uiName,"reg")
        LabelButton_6= EXUIControl.LabelButton(Form_1)
        Fun.Register(uiName,'PyMe_LabelButton_6',LabelButton_6,'login_bt')
        LabelButton_6.SetText("登录账号")
        LabelButton_6.SetBGColor("#FFFFFF")
        LabelButton_6.SetFGColor("#FFFFFF")
        LabelButton_6_TitleFont=tkinter.font.Font(family='微软雅黑', size=18,weight='normal',slant='roman',underline=0,overstrike=0)
        LabelButton_6.SetFont(LabelButton_6_TitleFont)
        LabelButton_6.SetBGImage("an.png")
        LabelButton_6.SetBGColor_Hover("#AAAAAA")
        LabelButton_6.SetFGColor_Hover("#000000")
        LabelButton_6.SetBGImage_Hover("an1.png")
        LabelButton_6.SetBGColor_Click("#AAAAAA")
        LabelButton_6.SetFGColor_Click("#FF0000")
        LabelButton_6.SetBGImage_Click("an2.png")
        Fun.SetControlPlace(uiName,'PyMe_LabelButton_6',0.6041666666666666,0.5277777777777778,0.2083,0.05333,'nw',True,True)
        LabelButton_6.Redraw()
        LabelButton_6.SetCommandFunction(login_main_cmd.login_bt_onCommand,self.uiName,"login_bt")
        LabelButton_18= EXUIControl.LabelButton(Form_1)
        Fun.Register(uiName,'PyMe_LabelButton_18',LabelButton_18,'LabelButton_4')
        LabelButton_18.SetText("配置升级，优惠不断！")
        LabelButton_18.SetBGColor("#FFFFFF")
        LabelButton_18.SetFGColor("#FFFFFF")
        LabelButton_18_TitleFont=tkinter.font.Font(family='微软雅黑', size=24,weight='normal',slant='roman',underline=0,overstrike=0)
        LabelButton_18.SetFont(LabelButton_18_TitleFont)
        LabelButton_18.SetBGImage("bn.png")
        LabelButton_18.SetBGColor_Hover("#FFFFFF")
        LabelButton_18.SetFGColor_Hover("#FFFFFF")
        LabelButton_18.SetBGImage_Hover("bn.png")
        LabelButton_18.SetBGColor_Click("#FFFFFF")
        LabelButton_18.SetFGColor_Click("#FFFFFF")
        LabelButton_18.SetBGImage_Click("bn.png")
        Fun.SetControlPlace(uiName,'PyMe_LabelButton_18',0.03263888888888889,0.6277777777777778,0.3167,0.05333,'nw',True,True)
        LabelButton_18.Redraw()
        LabelButton_21= EXUIControl.LabelButton(Form_1)
        Fun.Register(uiName,'PyMe_LabelButton_21',LabelButton_21,'LabelButton_5')
        LabelButton_21.SetText("忘记密码")
        LabelButton_21.SetBGColor("#FFFFFF")
        LabelButton_21.SetFGColor("#000000")
        LabelButton_21_TitleFont=tkinter.font.Font(family='Microsoft YaHei UI', size=18,weight='normal',slant='roman',underline=0,overstrike=0)
        LabelButton_21.SetFont(LabelButton_21_TitleFont)
        LabelButton_21.SetBGImage("Button.png")
        LabelButton_21.SetBGColor_Hover("#AAAAAA")
        LabelButton_21.SetFGColor_Hover("#000000")
        LabelButton_21.SetBGColor_Click("#AAAAAA")
        LabelButton_21.SetFGColor_Click("#FF0000")
        Fun.SetControlPlace(uiName,'PyMe_LabelButton_21',0.71875,0.6155555555555555,0.1111,0.0444,'nw',True,True)
        LabelButton_21.Redraw()
        LabelButton_21.SetCommandFunction(login_main_cmd.LabelButton_5_onCommand,self.uiName,"LabelButton_5")
        LabelButton_22= EXUIControl.LabelButton(Form_1)
        Fun.Register(uiName,'PyMe_LabelButton_22',LabelButton_22,'LabelButton_6')
        LabelButton_22.SetText("切换登录节点")
        LabelButton_22.SetBGColor("#FFFFFF")
        LabelButton_22.SetFGColor("#000000")
        LabelButton_22_TitleFont=tkinter.font.Font(family='微软雅黑', size=18,weight='normal',slant='roman',underline=0,overstrike=0)
        LabelButton_22.SetFont(LabelButton_22_TitleFont)
        LabelButton_22.SetBGColor_Hover("#AAAAAA")
        LabelButton_22.SetFGColor_Hover("#000000")
        LabelButton_22.SetBGColor_Click("#AAAAAA")
        LabelButton_22.SetFGColor_Click("#FF0000")
        Fun.SetControlPlace(uiName,'PyMe_LabelButton_22',0.6673611111111111,0.10222222222222223,0.1111,0.05333,'nw',True,True)
        LabelButton_22.Redraw()
        LabelButton_22.SetCommandFunction(login_main_cmd.LabelButton_6_onCommand,self.uiName,"LabelButton_6")
        Entry_5= EXUIControl.CustomEntry(Form_1)
        Fun.Register(uiName,'PyMe_Entry_5',Entry_5,'password')
        Entry_5.SetBGColor("#FFFFFF")
        Entry_5.SetBGColor_ReadOnly("#EFEFEF")
        Entry_5.SetFGColor("#000000")
        Entry_5_Font=tkinter.font.Font(family='微软雅黑', size=16,weight='normal',slant='roman',underline=0,overstrike=0)
        Entry_5.SetFont(Entry_5_Font)
        Entry_5.SetShowChar("●")
        Entry_5.SetTipText("密码")
        Entry_5.SetTipFGColor("#888888")
        Entry_5.SetRelief("sunken")
        Fun.SetControlPlace(uiName,'PyMe_Entry_5',0.6076388888888888,0.41888888888888887,0.1986111111111111,0.05333333333333334,'nw',True,True)
        Entry_9= EXUIControl.CustomEntry(Form_1)
        Fun.Register(uiName,'PyMe_Entry_9',Entry_9,'username')
        Entry_9.SetBGColor("#FFFFFF")
        Entry_9.SetBGColor_ReadOnly("#EFEFEF")
        Entry_9.SetFGColor("#000000")
        Entry_9_Font=tkinter.font.Font(family='微软雅黑', size=16,weight='normal',slant='roman',underline=0,overstrike=0)
        Entry_9.SetFont(Entry_9_Font)
        Entry_9.SetTipText("用户名或邮箱")
        Entry_9.SetTipFGColor("#888888")
        Entry_9.SetRelief("sunken")
        Fun.SetControlPlace(uiName,'PyMe_Entry_9',0.6076388888888888,0.3188888888888889,0.1986111111111111,0.05333333333333334,'nw',True,True)
        Label_13 = tkinter.Label(Form_1,text="Label")
        Fun.Register(uiName,'PyMe_Label_13',Label_13,'bg')
        Fun.SetControlPlace(uiName,'PyMe_Label_13',0.5694444444444444,0.15555555555555556,0.2708333333333333,0.5822222222222222,'nw',True,True)
        Label_13.configure(bg = "#FFFFFF")
        Label_13.configure(fg = "SystemButtonText")
        Fun.SetElementLayer(uiName,'bg',direction='lower')
        Label_14 = tkinter.Label(Form_1,text="恒星链接,畅玩MC")
        Fun.Register(uiName,'PyMe_Label_14',Label_14,'Label_4')
        Fun.SetControlPlace(uiName,'PyMe_Label_14',0.04791666666666667,218,0.325,0.05333,'nw',True,True)
        Label_14.configure(bg = "#FFFFFF")
        Label_14.configure(fg = "SystemButtonText")
        Label_14.configure(anchor = "w")
        Label_14_Ft=tkinter.font.Font(family='微软雅黑', size=25,weight='normal',slant='roman',underline=0,overstrike=0)
        Label_14.configure(font = Label_14_Ft)
        Label_15 = tkinter.Label(Form_1,text="全面/ 超广地区的节点")
        Fun.Register(uiName,'PyMe_Label_15',Label_15,'Label_5')
        Fun.SetControlPlace(uiName,'PyMe_Label_15',0.04861111111111111,0.31,0.18350000000000002,0.05333,'nw',True,True)
        Label_15.configure(bg = "#FFFFFF")
        Label_15.configure(fg = "SystemButtonText")
        Label_15_Ft=tkinter.font.Font(family='微软雅黑', size=16,weight='normal',slant='roman',underline=0,overstrike=0)
        Label_15.configure(font = Label_15_Ft)
        Label_16 = tkinter.Label(Form_1,text="持续/ 长期供应的节点")
        Fun.Register(uiName,'PyMe_Label_16',Label_16,'Label_6')
        Fun.SetControlPlace(uiName,'PyMe_Label_16',0.048600000000000004,0.3778,0.18350000000000002,0.05333333333333334,'nw',True,True)
        Label_16.configure(bg = "#FFFFFF")
        Label_16.configure(fg = "SystemButtonText")
        Label_16_Ft=tkinter.font.Font(family='微软雅黑', size=16,weight='normal',slant='roman',underline=0,overstrike=0)
        Label_16.configure(font = Label_16_Ft)
        Label_17 = tkinter.Label(Form_1,text="保障/ 稳定在线的客服")
        Fun.Register(uiName,'PyMe_Label_17',Label_17,'Label_7')
        Fun.SetControlPlace(uiName,'PyMe_Label_17',0.048600000000000004,0.44333333333333336,0.18350000000000002,0.05333,'nw',True,True)
        Label_17.configure(bg = "#FFFFFF")
        Label_17.configure(fg = "SystemButtonText")
        Label_17_Ft=tkinter.font.Font(family='微软雅黑', size=16,weight='normal',slant='roman',underline=0,overstrike=0)
        Label_17.configure(font = Label_17_Ft)
        Label_19 = tkinter.Label(Form_1,text="@2024 StellarLink")
        Fun.Register(uiName,'PyMe_Label_19',Label_19,'Label_8')
        Fun.SetControlPlace(uiName,'PyMe_Label_19',0.048600000000000004,0.5667,0.18350000000000002,0.05333,'nw',True,True)
        Label_19.configure(bg = "#FFFFFF")
        Label_19.configure(fg = "SystemButtonText")
        Label_19.configure(anchor = "w")
        Label_19_Ft=tkinter.font.Font(family='微软雅黑', size=16,weight='normal',slant='roman',underline=0,overstrike=0)
        Label_19.configure(font = Label_19_Ft)
        Label_20 = tkinter.Label(Form_1,text="")
        Fun.Register(uiName,'PyMe_Label_20',Label_20,'bg1')
        Fun.SetControlPlace(uiName,'PyMe_Label_20',0.71875,0.0,0.2813,1.0,'nw',True,True)
        Label_20.configure(bg = "#2468F2")
        Label_20.configure(fg = "SystemButtonText")
        Fun.SetElementLayer(uiName,'bg1',direction='lower')
        CheckButton_12_Variable = Fun.AddTKVariable(uiName,'PyMe_CheckButton_12')
        CheckButton_12_Variable.set(False)
        CheckButton_12 = tkinter.Checkbutton(Form_1,variable=CheckButton_12_Variable,text="记住密码",anchor=tkinter.W)
        Fun.Register(uiName,'PyMe_CheckButton_12',CheckButton_12,'CheckButton_1')
        Fun.SetControlPlace(uiName,'PyMe_CheckButton_12',0.6104166666666667,0.62,0.11109999999999999,0.04444,'nw',True,True)
        CheckButton_12.configure(bg = "#FFFFFF")
        CheckButton_12.configure(fg = "#000000")
        CheckButton_12.configure(activebackground = "#FFFFFF")
        CheckButton_12.configure(activeforeground = "#000000")
        CheckButton_12.configure(selectcolor = "#FFFFFF")
        Fun.SetCheckButtonSelectedColor(uiName,'PyMe_CheckButton_12','#FFFFFF','#000000')
        CheckButton_12_Ft=tkinter.font.Font(family='微软雅黑', size=18,weight='normal',slant='roman',underline=0,overstrike=0)
        CheckButton_12.configure(font = CheckButton_12_Ft)
        #Inital all element's Data 
        Fun.InitElementData(uiName)
        #Call Form_1's OnLoad Function
        Fun.RunForm1_CallBack(uiName,"Load",login_main_cmd.Form_1_onLoad)
        #Add Some Logic Code Here: (Keep This Line of comments)
        #Exit Application: (Keep This Line of comments)
        if self.isTKroot == True and Fun.GetElement(self.uiName,"root"):
            self.root.protocol('WM_DELETE_WINDOW', self.Exit)
            self.root.bind('<Configure>', self.Configure)
    def GetRootSize(self):
        return Fun.GetUIRootSize(self.uiName)
    def GetAllElement(self):
        return Fun.G_UIElementDictionary[self.uiName]
    def Escape(self,event):
        if Fun.AskBox('提示','确定退出程序？') == True:
            self.Exit()
    def Exit(self):
        if self.isTKroot == True:
            Fun.DestroyUI(self.uiName)
    def Configure(self,event):
        Form_1 = Fun.GetElement(self.uiName,'Form_1')
        if Form_1 == event.widget:
            Fun.ReDrawCanvasRecord(self.uiName)
        if self.root == event.widget:
            Fun.ResizeRoot(self.uiName,self.root,event)
            Fun.ResizeAllChart(self.uiName)
            uiName = self.uiName
            pass
        Fun.ActiveElement(self.uiName,event.widget)
#Create the root of Kinter 
if  __name__ == '__main__':
    Fun.RunApplication(login_main)
